# See https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template
#

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

zstyle ':omz:update' frequency 30

plugins=(\
        docker \
        docker-compose \
        fzf \
		git \
        systemd \
        zsh-autosuggestions \
        zsh-dircolors-solarized )

source $ZSH/oh-my-zsh.sh

export EDITOR=$(command -vp nvim 2> /dev/null || command -vp vi 2> /dev/null) 
export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR

if (( ${+commands[java]} ))
then
	export JAVA_HOME=$(java -XshowSettings:properties 2>&1 |grep java.home|awk '{print $3}')
fi

[[ -d /usr/local/go/bin ]] && export PATH=$PATH:/usr/local/go/bin
[[ -d ~/go/bin ]] && export PATH=$PATH:~/go/bin
[[ -d ~/bin ]] && export PATH=$PATH:~/bin


# To bind ctrl-space to accept autosuggest
bindkey '^ ' autosuggest-accept


### Re-assign 'z' to 'j' because j is easy to type with index finger and analogous for 'jump'
if [[ $(alias z | wc -w) == 2 ]]
then
	alias j='_z 2>&1'
fi

[[ -f ~/.local/zprofile ]] && source ~/.local/zprofile

if command -v zoxide &>/dev/null 
then
	eval "$(zoxide init --cmd j zsh)"
else
	plugins+=(z)
fi


# Stop homebrew from upgrading index while downloading new apps
HOMEBREW_NO_AUTO_UPDATE=1

