# See https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template
#

[[ -d /usr/local/go/bin ]] && export PATH=$PATH:/usr/local/go/bin
[[ -d ~/go/bin ]] && export PATH=$PATH:~/go/bin
[[ -d ~/bin ]] && export PATH=~/bin:$PATH
[[ -f ~/.local/zprofile ]] && source ~/.local/zprofile


### Completions need to be set before `compinit`
if command -v brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi


export ZSH="$HOME/.oh-my-zsh"
# Stop homebrew from upgrading index while downloading new apps
HOMEBREW_NO_AUTO_UPDATE=1
ZSH_THEME=simple

zstyle ':omz:update' frequency 30
export _Z_CMD=j

# Add plugins. The local zprofile might initialize some 
plugins+=(\
        docker \
        docker-compose \
	    git \
        systemd \
	    z \
        zsh-autosuggestions \
        zsh-dircolors-solarized )

if command -v fzf &> /dev/null
then
	plugins+=( fzf )
fi

source $ZSH/oh-my-zsh.sh

export EDITOR=$(command -vp nvim 2> /dev/null || command -vp vi 2> /dev/null) 
export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR

if command -v java &> /dev/null
then
	export JAVA_HOME=$(java -XshowSettings:properties 2>&1 |grep java.home|awk '{print $3}')
fi

# To bind ctrl-space to accept autosuggest
bindkey '^ ' autosuggest-accept

export PROMPT="%{$fg[green]%}%D{%H:%M:%S} %{$reset_color%}%{$fg_bold[red]%}♠ %m %{$reset_color%}%{$fg[green]%}%3~ %{$fg_bold[yellow]%}⇒ %{$reset_color%}"


if command -v zoxide &>/dev/null 
then
	eval "$(zoxide init --cmd j zsh)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

